### ISSUE TITLE
Find out tracking system

### ISSUE THREAD

**Issue by vlaksi** [vlaksi/JSZD-Proj#6]
## Description

- [x] Find the most suitable externe tracking system that could support our requirements (ie. have well-explained documentation and easy to use API)
- [x] write down a comparison between 2-3 possible systems that you find out
- [x] write down examples of how to use endpoints of the tracking system that you decided we should use 

## Acceptance criteria
- we understand how to use endpoint ie. API of the at least one tracking system (eg. we can test it with postman)

## Aditional information
- it's a separate issue, but leave a comment if you find out smth interest here: https://github.com/vlaksi/JSZD-Proj/issues/7
